import 'Strings.dart';

Map<String,String> localizedValueZH = {

  ID.CommonCancel : "取消",
  ID.CommonConfirm : "确认",
  ID.CommonPassword : "密码错误",
  ID.CommonBack : "再次返回,退出应用",
  ID.CommonSave : "保存",
  ID.CommonSaveSuccess : "保存成功",

  ID.CommonNetworkError : "网络请求失败",


  ID.CommonErrorEmpty : "暂无数据",
  ID.CommonErrorNetwork : "暂无数据",
  ID.CommonErrorSystem : "暂无数据",
  ID.CommonErrorVertify : "验证失败",
  ID.CommonCopy : "复制",
  ID.CommonShare : "分享",
  ID.CommonClipboard : "已复制到剪切板",
  ID.CommonRefuse : "拒绝",
  ID.CommonSuccess : "成功",
  ID.CommonFailed : "失败",
  ID.CommonSearch : "搜索",
  ID.CommonVersionTip : "已经是最新版本",
  ID.CommonVersionTip1 : "发现新版本",
  ID.CommonVersionTip2 : "正在下载",
  ID.CommonVersionUpdate : "立即更新",
  ID.CommonDeviceUnsupport : "设备不支持该功能",

  ID.CommonScanCode : "扫一扫",
  ID.CommonScanTip1 : "将相机对准二维码进行扫描",
  ID.CommonScanTip2 : "轻触打开灯",
  ID.CommonScanTip3 : "没有可用的摄像头",

  ID.Mine : "设置",
  ID.MineHome : "钱包",
  ID.MineTouchId : "Touch ID",
  ID.MineLanguage : "语言设置",
  ID.MinePrice : "货币单价",
  ID.MineSet : "通用设置",
  ID.MineConcert : "关注我们",
  ID.MineAbout : "关于我们",
  ID.MineFeedback : "意见反馈",
  ID.MineEmailUnistall : "未发现邮件客户端",
  ID.MineAboutVersion : "检查新版本",
  ID.MineAboutInfo : "ABEY作为全球领先的区块链公链平台，自主设计和开发的ABEYCHAIN成为开发者建立各种去中心化应用和商业应用的首选区块链。ABEYCHAIN作为ABEY的公共区块链基础架构，为多领域的去中心化应用程序提供简捷和安全可靠的区块链解决方案。 ABEY基金会将致力于管理、研究、指导、以及保持ABEYCHAIN技术在当今和未来的完整性和先进性。",
  ID.MineAboutProperty : "用户协议",
  ID.MinePropertyTip : "同意服务条款",
  ID.MinePropertySelect : "请阅读并同意服务协议",

  ID.MineTouchAuthTip : "请进行身份验证",
  ID.MineAddressBook : "地址簿",
  ID.MineAddressAdd : "添加地址",
  ID.MineAddressName : "名称",
  ID.MineAddressAddress : "地址",
  ID.MineAddressTipOne : "请输入钱包名称",
  ID.MineAddressTipTwo : "请输入正确的钱包地址",
  ID.MineAddressTipThree : "该钱包地址已添加",
  ID.MineAddressDelete : "删除",

  ID.WalletCreate : "创建钱包",
  ID.WalletImport : "导入钱包",
  ID.WalletRecovery : "恢复钱包",
  ID.WalletCreateTip : "创建一个新的钱包账户",
  ID.WalletImportTip : "导入已有的钱包账户",
  ID.WalletRecoveryTip : "恢复老版本钱包",

  ID.WalletCreateBtn : "创建",
  ID.WalletSelectChain : "选择主链",
  ID.WalletSelectChainMore : "添加更多主链",
  ID.WalletSelectChainTip : "请选择主链",

  ID.WalletCreateName : "钱包名称",
  ID.WalletCreateNameTip : "请输入正确的名称",

  ID.WalletRecoveryPsd : "原密码",
  ID.WalletRecoveryPsdTip : "请输入正确的原密码",

  ID.WalletCreatePsd : "密码",
  ID.WalletCreatePsdOk : "确认密码",
  ID.WalletCreatePsdTip : "请输入6位数字密码",
  ID.WalletCreatePsdTip1 : "两次密码不一致",
  ID.WalletCreatePsdTip2 : "密码不正确",
  ID.WalletCreatePsdSave : "请务必妥善保管好密码",

  ID.WalletCreateMnemonic : "新建助记词",
  ID.WalletBackupMnemonic : "备份助记词",
  ID.WalletBackupMnemonicTip1 : "确保备份正确,请按顺序记录助记词",
  ID.WalletBackupMnemonicTip2 : "请妥善保管助记词到安全地方，请勿将助记词在网络环境下传输",
  ID.WalletBackupMnemonicFinish : "完成备份",

  ID.WalletVertifyMnemonic : "验证助记词",
  ID.WalletVertifyMnemonicTip1 : "助记词的第{%s}个单词是什么",
  ID.WalletVertifyMnemonicTip2 : "请选择正确的单词",

  ID.WalletImportMnemonic : "助记词",
  ID.WalletImportPrivatekey : "私钥",
  ID.WalletImportKeystore : "Keystore",

  ID.WalletImportNameTip : "请输入钱包的名称",
  ID.WalletImportMnemonicTip : "请导入正确的助记词",
  ID.WalletImportMnemonicError : "导入助记词失败",
  ID.WalletImportPrivatekeyTip : "请导入正确的私钥",
  ID.WalletImportPrivatekeyError : "导入私钥失败",

  ID.WalletImportKeystoreFile : "Keystore content",
  ID.WalletImportKeystorePwd : "Keystore 密码",
  ID.WalletImportKeystorePwdTip : "请输入 Keystore 密码",
  ID.WalletImportKeystoreError : "请输入正确的 Keystore 文件内容",
  ID.WalletImportKeystoreErrorTip : "输入的 Keystore 文件内容或密码错误",

  ID.WalletList : "账户列表",
  ID.WalletAdd : "添加钱包",
  ID.WalletAddToken : "添加代币",

  ID.WalletTapAll : "全部",
  ID.WalletTapOut : "转出",
  ID.WalletTapIn : "转入",
  ID.WalletTapFailed : "失败",
  ID.WalletTokenDelete : "删除",

  ID.WalletTransfer : "转账",
  ID.WalletReceive : "接收",
  ID.WalletTrxBand : "带宽:",
  ID.WalletTrxEnergy : "能量:",
  ID.WalletSwap : "兑换",

  ID.WalletReceiveTip : "该地址仅支持 {##} 资产，请勿转入其他公链资产",
  ID.WalletScanTip : "扫描二维码转入",
  ID.WalletAddress : "钱包地址",
  ID.WalletTransferSuccess : "交易成功",
  ID.WalletTransferFailed : "交易失败",
  ID.WalletTransferDetail : "交易详情",

  ID.WalletTransferResult : "交易结果",
  ID.WalletTransferResultDetail : "查看详情",
  ID.WalletTransferResultTip1 : "交易发送成功",
  ID.WalletTransferResultTip2 : "交易发送失败",
  ID.WalletTransferResultTip3 : "等待区块验证，查看此交易的详细信息,请到区块链浏览器查看",
  ID.WalletTransferResultTip4 : "交易发送失败，请查看填入的交易参数是否正确",

  ID.WalletTransferInfo : "交易信息",
  ID.WalletTransferContractAddress : "合约地址",
  ID.WalletTransferReceiveAddress : "收款地址",
  ID.WalletTransferPayAddress : "付款地址",
  ID.WalletTransferGas : "矿工费用",
  ID.WalletTransferHash : "交易哈希",
  ID.WalletTransferLook : "查看详情",

  ID.WalletTransferNftTip : "转赠藏品",
  ID.WalletTransferNftTokenid : "Token ID:",
  ID.WalletTransferFee : "矿工费",
  ID.WalletTransferAmount : "数量",

  ID.WalletTransferTradeTime : "预计交易时间",
  ID.WalletTransferGasPrice : "Gas 价格",
  ID.WalletTransferAdvance : "Advance",
  ID.WalletTransferMin : "分钟",

  ID.WalletInputReceiveAddress : "请输入收款地址",
  ID.WalletInputAmount : "请输入转账数量",

  ID.WalletBalanceUnenough : "转账余额不足",
  ID.WalletTransferUnsupport : "暂不支持转账",
  ID.WalletTransferRemark : "备注",
  ID.WalletInputRemark : "请输入备注",

  ID.WalletTransferScan : "扫描二维码转入",
  ID.WalletModifyName : "修改钱包名称",
  ID.WalletLookPrivate : "查看私钥",
  ID.WalletLookKeystore : "查看Keystore",
  ID.WalletLookMnemonic : "查看助记词",
  ID.WalletManager : "钱包管理",
  ID.WalletDelete : "删除钱包",
  ID.WalletTransferRecord : "交易记录",
  ID.WalletTransferPending : "转账中",

  ID.WalletChainAdd : "请添加{%s}主链",
  ID.WalletAddSuccess : "添加成功",
  ID.WalletAllAssets : "总资产",
  ID.WalletMyAssets : "我的资产",
  ID.WalletAddChain : "添加主链",
  ID.WalletSupportChain : "支持ABEY...",
  ID.WalletTimeEstimated : "预计交易时间",

  ID.WalletTakeNot : "请勿截屏",
  ID.WalletTakeNotTip : "请勿截屏分享和存储,这将可能被第三方恶意软件收集,造成资产损失",
  ID.WalletGotIt : "显示助记词",
  ID.WalletAuthorization : "风险提示",
  ID.WalletTronExportTip : "不支持TRON主链导出Keystore",


  ID.Discover : "发现",
  ID.DiscoverTip : "Dapp将会使用您的钱包,确认将钱包信息提供给此网站吗?",
  ID.DiscoverSearch : "搜索DAPP",
  ID.DiscoverSearchTip : "输入DAPP网址",
  ID.DiscoverSearchTip1 : "请输入搜索内容",
  ID.DiscoverComment : "大家都在搜",
  ID.DiscoverSearchHistory : "搜索历史",

  ID.Kyf : "NFT",
  ID.KyfFloorPrice : "地板价",
  ID.KyfTokenId : "Token Id:",
  ID.KyfShow : "显示",
  ID.KyfDetail : "详情",
  ID.KyfPiece : "件",

  ID.KyfTransfer : "转赠",
  ID.KyfReceive : "接收",

};