import 'Strings.dart';

Map<String,String> localizedValueEN = {

  ID.CommonCancel : "Cancel",
  ID.CommonConfirm : "Confirm",
  ID.CommonPassword : "Wrong password",
  ID.CommonBack : "Go back again and exit the app",
  ID.CommonSave : "Save",
  ID.CommonSaveSuccess : "Saved successfully",

  ID.CommonNetworkError : "Network request failed",

  ID.CommonErrorNetwork : "Network connection failure~",
  ID.CommonErrorSystem : "System maintenance in progress~",
  ID.CommonErrorEmpty : "Sorry, there is no data at present",
  ID.CommonErrorVertify : "Vertify failed",
  ID.CommonCopy : "Copy",
  ID.CommonShare : "Share",
  ID.CommonClipboard : "Copied to clipboard",
  ID.CommonRefuse : "Reject",
  ID.CommonSuccess : "Success",
  ID.CommonFailed : "Failed",
  ID.CommonSearch : "Search",
  ID.CommonVersionTip : "It is already the latest version",
  ID.CommonVersionTip1 : "New version found",
  ID.CommonVersionTip2 : "Downloading",
  ID.CommonVersionUpdate : "Update",
  ID.CommonDeviceUnsupport : "The device does not support this function",

  ID.CommonScanCode : "Scan QR Code",
  ID.CommonScanTip1 : "Aim your camera to the QR Code to scan",
  ID.CommonScanTip2 : "Tap to turn light on",
  ID.CommonScanTip3 : "No camera available",

  ID.Mine : "Settings",
  ID.MineHome : "Wallet",
  ID.MineTouchId : "Touch ID",
  ID.MineLanguage : "Language settings",
  ID.MinePrice : "Currency Price",
  ID.MineSet : "General settings",
  ID.MineConcert : "Follow us",
  ID.MineAbout : "About Us",
  ID.MineFeedback : "Feedback",
  ID.MineEmailUnistall : "No mail client found",
  ID.MineAboutVersion : "Version",
  ID.MineAboutInfo : "As the world's leading blockchain public chain platform, ABEYCHAIN, independently designed and developed, has become the preferred blockchain for developers to build various decentralized applications and commercial applications. ABEYCHAIN, as ABEY's public blockchain infrastructure, is dedicated to the management, research, guidance, and maintenance of ABEYCHAIN ​​technology today and in the future.",
  ID.MineAboutProperty : "User Agreement",
  ID.MinePropertyTip : "Agree to the terms of service",
  ID.MinePropertySelect : "Please read and agree to the service agreement first",

  ID.MineTouchAuthTip : "Please authenticate",
  ID.MineAddressBook : "Address Book",
  ID.MineAddressAdd : "Add Address",
  ID.MineAddressName : "Name",
  ID.MineAddressAddress : "Address",
  ID.MineAddressTipOne : "Please enter the wallet name",
  ID.MineAddressTipTwo : "Please enter the correct wallet address",
  ID.MineAddressTipThree : "The wallet address has been added",
  ID.MineAddressDelete : "Delete",

  ID.WalletCreate : "Create Wallet",
  ID.WalletImport : "Import Wallet",
  ID.WalletRecovery : "Restore Wallet",
  ID.WalletCreateTip : "Create a new wallet",
  ID.WalletImportTip : "Import an existing wallet",
  ID.WalletRecoveryTip : "Restore old wallet",

  ID.WalletCreateBtn : "Create",
  ID.WalletSelectChain : "Select the main chain",
  ID.WalletSelectChainMore : "Add more blockchain",
  ID.WalletSelectChainTip : "Please select the main chain",

  ID.WalletCreateName : "Wallet Name",
  ID.WalletCreateNameTip : "Please enter the correct name",

  ID.WalletRecoveryPsd : "Original password",
  ID.WalletRecoveryPsdTip : "Please enter the original password",

  ID.WalletCreatePsd : "Password",
  ID.WalletCreatePsdOk : "Check Password",
  ID.WalletCreatePsdTip : "Please enter a 6-digit password",
  ID.WalletCreatePsdTip1 : "Two passwords are not consistent",
  ID.WalletCreatePsdTip2 : "Wrong password",
  ID.WalletCreatePsdSave : "Please keep your password properly",

  ID.WalletCreateMnemonic : "New mnemonic",
  ID.WalletBackupMnemonic : "Backup mnemonic",
  ID.WalletBackupMnemonicTip1 : "Make sure the backup is correct, record mnemonics in order",
  ID.WalletBackupMnemonicTip2 : "Please keep mnemonics in a safe place. Do not transmit mnemonics in the network environment",
  ID.WalletBackupMnemonicFinish : "Complete backup",

  ID.WalletVertifyMnemonic : "Verify mnemonic word",
  ID.WalletVertifyMnemonicTip1 : "What is the {%s}th word of the mnemonic?",
  ID.WalletVertifyMnemonicTip2 : "Please choose the correct word",

  ID.WalletImportMnemonic : "Mnemonic",
  ID.WalletImportPrivatekey : "Private key",
  ID.WalletImportKeystore : "Keystore",

  ID.WalletImportNameTip : "Please enter the name of the wallet",
  ID.WalletImportMnemonicTip : "Please import the correct mnemonic",
  ID.WalletImportMnemonicError : "Failed to import mnemonic",
  ID.WalletImportPrivatekeyTip : "Please import the correct private key",
  ID.WalletImportPrivatekeyError : "Failed to import private key",

  ID.WalletImportKeystoreFile : "Keystore content",
  ID.WalletImportKeystorePwd : "Keystore password",
  ID.WalletImportKeystorePwdTip : "Please input keystore password",
  ID.WalletImportKeystoreError : "Please input the correct keystore file content",
  ID.WalletImportKeystoreErrorTip : "Input keysore file content or password error",

  ID.WalletList : "Wallet List",
  ID.WalletAdd : "Add wallet",
  ID.WalletAddToken : "Add token",

  ID.WalletTapAll : "all",
  ID.WalletTapOut : "out",
  ID.WalletTapIn : "in",
  ID.WalletTapFailed : "fail",
  ID.WalletTokenDelete : "Delete",

  ID.WalletTransfer : "Transfer",
  ID.WalletReceive : "Receive",
  ID.WalletTrxBand : "Bandwidth:",
  ID.WalletTrxEnergy : "Energy:",
  ID.WalletSwap : "Swap",

  ID.WalletReceiveTip : "This address only supports {##} assets, please do not transfer assets from other public chains",
  ID.WalletScanTip : "Scan QR code to transfer",
  ID.WalletAddress : "Wallet Address",
  ID.WalletTransferSuccess : "Transfer Successfully",
  ID.WalletTransferFailed : "Transaction failed",
  ID.WalletTransferDetail : "Transaction details",

  ID.WalletTransferResult : "Trading results",
  ID.WalletTransferResultDetail : "View Details",
  ID.WalletTransferResultTip1 : "Transaction sent successfully",
  ID.WalletTransferResultTip2 : "Transaction sending failed",
  ID.WalletTransferResultTip3 : "Wait for block verification to view the details of this transaction. Please go to the blockchain browser to view",
  ID.WalletTransferResultTip4 : "Transaction sending failed. Please check whether the transaction parameters filled in are correct",

  ID.WalletTransferInfo : "Transaction info",
  ID.WalletTransferContractAddress : "Contract Address",
  ID.WalletTransferReceiveAddress : "Receive Address",
  ID.WalletTransferPayAddress : "Payment Address",
  ID.WalletTransferGas : "Gas Fee",
  ID.WalletTransferHash : "Hash",
  ID.WalletTransferLook : "View Details",

  ID.WalletTransferNftTip : "Transfer Collection",
  ID.WalletTransferNftTokenid : "Token ID:",
  ID.WalletTransferFee : "Gas Fee",
  ID.WalletTransferAmount : "Amount",
  ID.WalletTransferTradeTime : "Estimated Transaction Time",
  ID.WalletTransferGasPrice : "Gas Price",
  ID.WalletTransferAdvance : "Advance",
  ID.WalletTransferMin : "min",

  ID.WalletInputReceiveAddress : "Input the address of receiver",
  ID.WalletInputAmount : "Please enter the transfer amount",

  ID.WalletBalanceUnenough : "Insufficient transfer balance",
  ID.WalletTransferUnsupport : "Does not support transfers temporarily",
  ID.WalletTransferRemark : "Remarks",
  ID.WalletInputRemark : "Transfer Remarks Tip",

  ID.WalletTransferScan : "Scan QR code to transfer",
  ID.WalletModifyName : "Modify wallet name",
  ID.WalletLookPrivate : "Private Key",
  ID.WalletLookKeystore : "Keystore content",
  ID.WalletLookMnemonic : "Mnemonic",
  ID.WalletManager : "Wallet Management",
  ID.WalletDelete : "Delete wallet",
  ID.WalletTransferRecord : "Transaction record",
  ID.WalletTransferPending : "Pending",

  ID.WalletChainAdd : "Please add {%s} main chain",
  ID.WalletAddSuccess : "Added successfully",
  ID.WalletAllAssets : "Total Assets",
  ID.WalletMyAssets : "My Assets",
  ID.WalletAddChain : "Add Chain",
  ID.WalletSupportChain : "Support ABEY...",
  ID.WalletTimeEstimated : "Estimated Transaction Time",

  ID.WalletTakeNot : "Don't take a screenshot",
  ID.WalletTakeNotTip : "Do not take screenshots to share or store, which may be collected by third-party malware and cause asset loss",
  ID.WalletGotIt : "Got it",
  ID.WalletAuthorization : "Risk statement",
  ID.WalletTronExportTip : "The export of Keystore from the TRON main chain is not supported",


  ID.Discover : "Discover",
  ID.DiscoverTip : "DAPP will use your wallet. Are you sure to provide wallet information to this website?",
  ID.DiscoverSearch : "Search DAPP",
  ID.DiscoverSearchTip : "Enter DAPP web address",
  ID.DiscoverSearchTip1 : "Please enter the search content",
  ID.DiscoverComment : "Everyone is searching",
  ID.DiscoverSearchHistory : "Search history",

  ID.Kyf : "NFT",
  ID.KyfFloorPrice : "Floor price",
  ID.KyfTokenId : "Token Id:",
  ID.KyfShow : "Show",
  ID.KyfDetail : "Detail",
  ID.KyfPiece : "Piece",

  ID.KyfTransfer : "Transfer",
  ID.KyfReceive : "Receive",

};