import 'Strings.dart';

Map<String,String> localizedValueKO = {

  ID.CommonCancel : "취소",
  ID.CommonConfirm : "확인",
  ID.CommonPassword : "비밀번호 오류",
  ID.CommonBack : "다시 돌아가서 앱을 종료하십시오.",
  ID.CommonSave : "저장",
  ID.CommonSaveSuccess : "저장 성공",

  ID.CommonNetworkError : "네트워크 요청 실패",

  ID.CommonErrorEmpty : "네트워크 연결 실패",
  ID.CommonErrorNetwork : "시스템 점검 중",
  ID.CommonErrorSystem : "데이터 없음",
  ID.CommonErrorVertify : "인증 실패",
  ID.CommonCopy : "복사",
  ID.CommonShare : "공유",
  ID.CommonClipboard : "클립보드에 복사",
  ID.CommonRefuse : "거절",
  ID.CommonSuccess : "성공",
  ID.CommonFailed : "실패",
  ID.CommonSearch : "검색",
  ID.CommonVersionTip : "이미 최신 버전입니다.",
  ID.CommonVersionTip1 : "새 버전",
  ID.CommonVersionTip2 : "다운로드 중",
  ID.CommonVersionUpdate : "지금 업데이트",
  ID.CommonDeviceUnsupport : "장치가 이 기능을 지원하지 않습니다.",

  ID.CommonScanCode : "QR 코드 스캔",
  ID.CommonScanTip1 : "스캔할 QR 코드에 카메라를 맞추세요.",
  ID.CommonScanTip2 : "클릭하여 조명 켜기",
  ID.CommonScanTip3 : "사용 가능한 카메라가 없음",

  ID.Mine : "설정",
  ID.MineHome : "지갑",
  ID.MineTouchId : "ID 터치",
  ID.MineLanguage : "언어 설정",
  ID.MinePrice : "통화 가격",
  ID.MineSet : "일반 설정",
  ID.MineConcert : "팔로우하기",
  ID.MineAbout : "회사 소개",
  ID.MineFeedback : "피드백",
  ID.MineEmailUnistall : "메일을 찾을 수 없음",
  ID.MineAboutVersion : "버전",
  ID.MineAboutInfo : "세계 최고의 블록체인 퍼블릭 체인 플랫폼인 ABEYCHAIN은 독립적으로 설계 및 개발되었으며 개발자가 다양한 분산 애플리케이션 및 상용 애플리케이션을 구축하는 데 선호되는 블록체인이 되었습니다. ABEY의 퍼블릭 블록체인 인프라인 ABEYCHAIN은 현재와 미래의 ABEYCHAIN ​​기술의 관리, 연구, 안내 및 유지 관리에 전념합니다.",
  ID.MineAboutProperty : "사용자 약관",
  ID.MinePropertyTip : "이용 약관에 동의",
  ID.MinePropertySelect : "이용 약관을 읽고 동의 하십시오",

  ID.MineTouchAuthTip : "인증하십시오.",
  ID.MineAddressBook : "주소록",
  ID.MineAddressAdd : "주소 추가",
  ID.MineAddressName : "이름",
  ID.MineAddressAddress : "주소",
  ID.MineAddressTipOne : "지갑 이름을 입력하십시오.",
  ID.MineAddressTipTwo : "올바른 지갑 주소를 입력하십시오.",
  ID.MineAddressTipThree : "지갑 주소가 추가되었습니다.",
  ID.MineAddressDelete : "삭제",

  ID.WalletCreate : "지갑 생성",
  ID.WalletImport : "지갑 가져오기",
  ID.WalletRecovery : "지갑 복구",
  ID.WalletCreateTip : "새 지갑 생성하기",
  ID.WalletImportTip : "기존 지갑 가져오기",
  ID.WalletRecoveryTip : "이전 버전 지갑 복구",

  ID.WalletCreateBtn : "생성",
  ID.WalletSelectChain : "메인 체인 선택.",
  ID.WalletSelectChainMore : "더 많은 메인 체인 추가",
  ID.WalletSelectChainTip : "메인 체인을 선택하십시오.",

  ID.WalletCreateName : "지갑 명칭",
  ID.WalletCreateNameTip : "정확한 명칭을 입력하십시오.",

  ID.WalletRecoveryPsd : "원래 암호",
  ID.WalletRecoveryPsdTip : "원래 암호를 입력하십시오.",

  ID.WalletCreatePsd : "비밀번호",
  ID.WalletCreatePsdOk : "비밀번호 확인",
  ID.WalletCreatePsdTip : "6자리 비밀번호를 입력하십시오.",
  ID.WalletCreatePsdTip1 : "두 비밀번호가 일치하지 않습니다.",
  ID.WalletCreatePsdTip2 : "비밀번호 오류",
  ID.WalletCreatePsdSave : "비밀번호를 잘 보관하십시오.",

  ID.WalletCreateMnemonic : "새 니모닉",
  ID.WalletBackupMnemonic : "백업 니모닉",
  ID.WalletBackupMnemonicTip1 : "백업이 잘 되었는지 그리고 니모닉을 순서대로 잘 기록했는지 확인하십시오.",
  ID.WalletBackupMnemonicTip2 : "니모닉을 안전한 곳에 잘 보관하십시오.  니모닉을 네트워크 환경에서 전송하지 마십시오.",
  ID.WalletBackupMnemonicFinish : "백업 완료",

  ID.WalletVertifyMnemonic : "니모닉 단어 확인",
  ID.WalletVertifyMnemonicTip1 : "니모닉 코드의 {%s}번째 단어는 무엇입니까?",
  ID.WalletVertifyMnemonicTip2 : "올바른 단어를 선택하십시오.",

  ID.WalletImportMnemonic : "니모닉 코드",
  ID.WalletImportPrivatekey : "개인 보안키",
  ID.WalletImportKeystore : "키스토어",

  ID.WalletImportNameTip : "지갑의 이름을 입력하세요",
  ID.WalletImportMnemonicTip : "정확한 니모닉 불러오기",
  ID.WalletImportMnemonicError : "니모닉 가져오기 실패",
  ID.WalletImportPrivatekeyTip : "정확한 개인보안키 불러오기",
  ID.WalletImportPrivatekeyError : "개인보안키 불러오기 실패",

  ID.WalletImportKeystoreFile : "키스토어 파일 내용",
  ID.WalletImportKeystorePwd : "키스토어 비밀번호",
  ID.WalletImportKeystorePwdTip : "키스토어 비밀번호 입력",
  ID.WalletImportKeystoreError : "정확한 키스토어 파일 내용을 입력하십시오.",
  ID.WalletImportKeystoreErrorTip : "입력하신 키스토어 파일 내용이나 비밀번호 오류",

  ID.WalletList : "지갑 목록",
  ID.WalletAdd : "지갑 추가",
  ID.WalletAddToken : "토큰 추가",

  ID.WalletTapAll : "전액",
  ID.WalletTapOut : "출금",
  ID.WalletTapIn : "입금",
  ID.WalletTapFailed : "실패",
  ID.WalletTokenDelete : "삭제",

  ID.WalletTransfer : "이체",
  ID.WalletReceive : "받다",
  ID.WalletTrxBand : "대역폭:",
  ID.WalletTrxEnergy : "에너지:",
  ID.WalletSwap : "교환",

  ID.WalletReceiveTip : "이 주소는 {##} 자산만 지원하므로 다른 퍼블릭 체인으로부터 자산을 전송하지 마십시오.",
  ID.WalletScanTip : "QR 코드를 스캔하여 이체하기",
  ID.WalletAddress : "지갑 주소",
  ID.WalletTransferSuccess : "이체 성공",
  ID.WalletTransferFailed : "거래 실패",
  ID.WalletTransferDetail : "거래 내역",

  ID.WalletTransferResult : "거래 결과",
  ID.WalletTransferResultDetail : "세부 정보 보기",
  ID.WalletTransferResultTip1 : "거래 발송 성공",
  ID.WalletTransferResultTip2 : "거래 발송 실패",
  ID.WalletTransferResultTip3 : "블록 검증을 기다리고 이 거래에 대한 자세한 정보를 보려면 블록체인 브라우저에서 확인하십시오",
  ID.WalletTransferResultTip4 : "거래 발송에 실패했습니다. 입력된 거래 매개 변수가 정확한지 확인하십시오.",

  ID.WalletTransferInfo : "거래 정보",
  ID.WalletTransferContractAddress : "거래 주소",
  ID.WalletTransferReceiveAddress : "입금 주소",
  ID.WalletTransferPayAddress : "지불 주소",
  ID.WalletTransferGas : "가스비용",
  ID.WalletTransferHash : "해쉬",
  ID.WalletTransferLook : "세부 정보 보기",

  ID.WalletTransferNftTip : "전송 모음",
  ID.WalletTransferNftTokenid : "토큰 ID:",
  ID.WalletTransferFee : "가스 비용",
  ID.WalletTransferAmount : "수량",
  ID.WalletTransferTradeTime : "예상 거래 시간",
  ID.WalletTransferGasPrice : "가스 가격",
  ID.WalletTransferAdvance : "빠른 전송",
  ID.WalletTransferMin : "분",

  ID.WalletInputReceiveAddress : "입금 주소 입력",
  ID.WalletInputAmount : "이체 금액을 입력하십시오.",

  ID.WalletBalanceUnenough : "잔고 부족",
  ID.WalletTransferUnsupport : "이체 불가능",
  ID.WalletTransferRemark : "메모",
  ID.WalletInputRemark : "이체 메모 입력",

  ID.WalletTransferScan : "QR 코드를 스캔하여 이체하기",
  ID.WalletModifyName : "지갑 명칭 수정하기",
  ID.WalletLookPrivate : "개인보안키",
  ID.WalletLookKeystore : "키스토어 파일 보기",
  ID.WalletLookMnemonic : "니모닉",
  ID.WalletManager : "지갑 관리",
  ID.WalletDelete : "지갑 삭제",
  ID.WalletTransferRecord : "거래 기록",
  ID.WalletTransferPending : "전송 중",

  ID.WalletChainAdd : "{%s} 메인 체인을 추가하십시오",
  ID.WalletAddSuccess : "성공적으로 추가되었습니다.",
  ID.WalletAllAssets : "총 자산",
  ID.WalletMyAssets : "나의 자산",
  ID.WalletAddChain : "체인 추가",
  ID.WalletSupportChain : "ABEY 지원",
  ID.WalletTimeEstimated : "예상 거래 시간",

  ID.WalletTakeNot : "화면을 캡처하지 마십시오.",
  ID.WalletTakeNotTip : "화면을 공유하거나 저장하기 위해 스크린샷을 찍지 마십시오. 악성코드에 노출되어 자산이 손실될 수 있습니다.",
  ID.WalletGotIt : "알겠습니다.",
  ID.WalletAuthorization : "위험 알림",
  ID.WalletTronExportTip : "TRON 마스터 체인 내보내기 Keystore는 지원되지 않습니다.",


  ID.Discover : "발견",
  ID.DiscoverTip : "Dapp에서 귀하의 지갑이 사용될 것입니다. 이 웹사이트에 지갑 정보를 제공하시겠습니까?",
  ID.DiscoverSearch : "DAPP 검색",
  ID.DiscoverSearchTip : "DAPP 웹 주소를 입력 하십시오.",
  ID.DiscoverSearchTip1 : "검색 내용 입력",
  ID.DiscoverComment : "모두 검색 중",
  ID.DiscoverSearchHistory : "기록 검색",

  ID.Kyf : "NFT",
  ID.KyfFloorPrice : "마루값",
  ID.KyfTokenId : "Token Id:",
  ID.KyfShow : "보여 주다",
  ID.KyfDetail : "세부 사항",
  ID.KyfPiece : "건수",

  ID.KyfTransfer : "돌려주다",
  ID.KyfReceive : "받다",

};