import 'Strings.dart';

Map<String,String> localizedValueJA = {

  ID.CommonCancel : "キャンセル",
  ID.CommonConfirm : "承認",
  ID.CommonPassword : "間違ったパスワード",
  ID.CommonBack : "再度元に戻りアプリから退出",
  ID.CommonSave : "保存",
  ID.CommonSaveSuccess : "保存に成功しました",

  ID.CommonNetworkError : "ネットワークリクエスト失敗",

  ID.CommonErrorNetwork : "ネットワーク接続失敗~",
  ID.CommonErrorSystem : "システムメンテナンス中~",
  ID.CommonErrorEmpty : "申し訳ありません。現在データはありません",
  ID.CommonErrorVertify : "承認失敗",
  ID.CommonCopy : "コピー",
  ID.CommonShare : "共有",
  ID.CommonClipboard : "クリップボードへコピー",
  ID.CommonRefuse : "却下",
  ID.CommonSuccess : "成功",
  ID.CommonFailed : "失敗",
  ID.CommonSearch : "検索",
  ID.CommonVersionTip : "既に最新版です",
  ID.CommonVersionTip1 : "新バージョンが見つかりました",
  ID.CommonVersionTip2 : "ダウンロード中",
  ID.CommonVersionUpdate : "アップデート",
  ID.CommonDeviceUnsupport : "デバイスはこの機能をサポートしていません",

  ID.CommonScanCode : "QRコードをスキャン",
  ID.CommonScanTip1 : "カメラをQRコードに向けスキャンする",
  ID.CommonScanTip2 : "タップしライトをオンにする",
  ID.CommonScanTip3 : "利用可能なカメラがありません",

  ID.Mine : "設定",
  ID.MineHome : "ウォレット",
  ID.MineTouchId : "タッチ ID",
  ID.MineLanguage : "言語設定",
  ID.MinePrice : "通貨価格",
  ID.MineSet : "汎用設定",
  ID.MineConcert : "フォローする",
  ID.MineAbout : "私共に関して",
  ID.MineFeedback : "フィードバック",
  ID.MineEmailUnistall : "メールクライアントが見つかりません",
  ID.MineAboutVersion : "バージョン",
  ID.MineAboutInfo : "世界をリードするブロックチェーン、パブリックブロックチェーンプラットフォームとして、独自設計及び開発されたABEYCHAINは、開発者が様々な分散型アプリケーションや商用アプリケーションを構築する為の推奨ブロックチェーンとなりました。 ABEYCHAINは、ABEYパブリックブロックチェーンインフラストラクチャとし、現在並びに将来のABEYCHAINテクノロジーの管理、調査、ガイダンス、及びメンテナンスに取り組んでいます",
  ID.MineAboutProperty : "ユーザー規約",
  ID.MinePropertyTip : "利用規約に同意する",
  ID.MinePropertySelect : "最初にサービス規約をお読みの上、ご同意下さい",

  ID.MineTouchAuthTip : "認証してください",
  ID.MineAddressBook : "アドレス帳",
  ID.MineAddressAdd : "アドレスを追加",
  ID.MineAddressName : "の名前をあげる",
  ID.MineAddressAddress : "アドレス",
  ID.MineAddressTipOne : "ウォレット名を入力してください",
  ID.MineAddressTipTwo : "正しいウォレットアドレスを入力してください",
  ID.MineAddressTipThree : "ウォレットアドレスが追加されました",
  ID.MineAddressDelete : "削除",

  ID.WalletCreate : "ウォレットを作成",
  ID.WalletImport : "ウォレットをインポート",
  ID.WalletRecovery : "ウォレットを復元",
  ID.WalletCreateTip : "新しいウォレットを作成",
  ID.WalletImportTip : "既存ウォレットをインポート",
  ID.WalletRecoveryTip : "古いウォレットを復元",

  ID.WalletCreateBtn : "作成",
  ID.WalletSelectChain : "メインチェーンを選択",
  ID.WalletSelectChainMore : "メインチェーンを追加する",
  ID.WalletSelectChainTip : "メインチェーンを選択して下さい",

  ID.WalletCreateName : "ウォレット名",
  ID.WalletCreateNameTip : "正しい名前を入れて下さい",

  ID.WalletRecoveryPsd : "元のパスワード",
  ID.WalletRecoveryPsdTip : "元のパスワードを入れて下さい",

  ID.WalletCreatePsd : "パスワード",
  ID.WalletCreatePsdOk : "パスワードを確認",
  ID.WalletCreatePsdTip : "6桁のパスワードを入れて下さい",
  ID.WalletCreatePsdTip1 : " 2つのパスワードが一致しません",
  ID.WalletCreatePsdTip2 : "誤ったパスワード",
  ID.WalletCreatePsdSave : "パスワードを正しく保管して下さい",

  ID.WalletCreateMnemonic : "新二モニック",
  ID.WalletBackupMnemonic : "二モニックをバックアップ",
  ID.WalletBackupMnemonicTip1 : "バックアップが正しい事を確認し、ニモニックを順番通りに記録する",
  ID.WalletBackupMnemonicTip2 : "ニモニックは安全な場所に保管して下さい。 ネットワーク環境でニモニックを送信しないで下さい",
  ID.WalletBackupMnemonicFinish : "バックアップ完了",

  ID.WalletVertifyMnemonic : "ニモニックの言葉を承認",
  ID.WalletVertifyMnemonicTip1 : "二モニックで {%s} の言葉は何ですか?",
  ID.WalletVertifyMnemonicTip2 : "正しい言葉をご選択下さい",

  ID.WalletImportMnemonic : "二モニック",
  ID.WalletImportPrivatekey : "プライベートキー",
  ID.WalletImportKeystore : "キーストア",

  ID.WalletImportNameTip : "ウオレット名を入力下さい",
  ID.WalletImportMnemonicTip : "正しい二モニックをインポートして下さい",
  ID.WalletImportMnemonicError : "二モニックインポート失敗",
  ID.WalletImportPrivatekeyTip : "正しいプライベートキーをインポートして下さい",
  ID.WalletImportPrivatekeyError : "プライベートキーインポートに失敗",

  ID.WalletImportKeystoreFile : "キーストア内容",
  ID.WalletImportKeystorePwd : "キーストアパスワード",
  ID.WalletImportKeystorePwdTip : "キーストアパスワードを入力下さい",
  ID.WalletImportKeystoreError : "正しいキーストアファイル内容を入力下さい",
  ID.WalletImportKeystoreErrorTip : "入力キーストアファイル内容又はパスワードエラー",

  ID.WalletList : "ウォレットリスト",
  ID.WalletAdd : "ウォレットを追加",
  ID.WalletAddToken : "トークンを追加",

  ID.WalletTapAll : "全部",
  ID.WalletTapOut : "出す",
  ID.WalletTapIn : "入れる",
  ID.WalletTapFailed : "失敗",
  ID.WalletTokenDelete : "削除",

  ID.WalletTransfer : "転送",
  ID.WalletReceive : "受入",
  ID.WalletTrxBand : "バンドワイド:",
  ID.WalletTrxEnergy : "エネルギー:",
  ID.WalletSwap : "スワップ",

  ID.WalletReceiveTip : "このアドレスは{##} アセットのみをサポートします。他のパブリックチェーンからアセットを転送しないで下さい",
  ID.WalletScanTip : " QRコードをスキャンして転送",
  ID.WalletAddress : "ウォレットアドレス",
  ID.WalletTransferSuccess : "転送成功",
  ID.WalletTransferFailed : "転送失敗",
  ID.WalletTransferDetail : "転送詳細",

  ID.WalletTransferResult : "取引結果",
  ID.WalletTransferResultDetail : "プロフィール詳細",
  ID.WalletTransferResultTip1 : "送信成功",
  ID.WalletTransferResultTip2 : "送信に失敗しました",
  ID.WalletTransferResultTip3 : "ブロック検証を待って、この取引の詳細を表示します。ブロックチェーンブラウザで表示してください",
  ID.WalletTransferResultTip4 : "トランザクション送信に失敗しました。入力したトランザクションパラメータが正しいかどうかを確認してください",

  ID.WalletTransferInfo : "転送情報",
  ID.WalletTransferContractAddress : "コントラクトアドレス",
  ID.WalletTransferReceiveAddress : "アドレスを受け取る",
  ID.WalletTransferPayAddress : "支払いアドレス",
  ID.WalletTransferGas : "ガス料",
  ID.WalletTransferHash : "ハッシュ",
  ID.WalletTransferLook : "詳細を見る",

  ID.WalletTransferNftTip : "転送コレクション",
  ID.WalletTransferNftTokenid : "トークン ID:",
  ID.WalletTransferFee : "ガス料",
  ID.WalletTransferAmount : "量",
  ID.WalletTransferTradeTime : "推定トランザクション時間",
  ID.WalletTransferGasPrice : "ガス価格",
  ID.WalletTransferAdvance : "事前",
  ID.WalletTransferMin : "分",

  ID.WalletInputReceiveAddress : "受け取り者のアドレスを入力",
  ID.WalletInputAmount : "転送額を入力下さい",

  ID.WalletBalanceUnenough : "不十分な転送残高",
  ID.WalletTransferUnsupport : "一時的に転送をサポートしていません",
  ID.WalletTransferRemark : "備考",
  ID.WalletInputRemark : "転送備考のヒント",

  ID.WalletTransferScan : " QRコードをスキャンして転送",
  ID.WalletModifyName : "ウォレット名を変更",
  ID.WalletLookPrivate : "プライベートキー",
  ID.WalletLookKeystore : "キーストア内容",
  ID.WalletLookMnemonic : "二モニック",
  ID.WalletManager : "ウォレット管理",
  ID.WalletDelete : "ウォレットを削除",
  ID.WalletTransferRecord : "トランザクション記録",
  ID.WalletTransferPending : "保留中",

  ID.WalletChainAdd : "{%s}メインチェーンを追加して下さい",
  ID.WalletAddSuccess : "追加成功",
  ID.WalletAllAssets : "合計アセット",
  ID.WalletMyAssets : "私のアセット",
  ID.WalletAddChain : "チェーンを追加",
  ID.WalletSupportChain : "ABEYをサポート",
  ID.WalletTimeEstimated : "予想トランザクション時間",

  ID.WalletTakeNot : "スクリーンショットを撮らないで下さい",
  ID.WalletTakeNotTip : "第三機関マルウェアによって収集され、アセット損失を引き起こす可能性がありますので、スクリーンショットを共有又は保存しないで下さい",
  ID.WalletGotIt : "了解",
  ID.WalletAuthorization : "リスクステートメント",
  ID.WalletTronExportTip : "TRON主鎖エクスポートKeystoreはサポートされていません",


  ID.Discover : "発見",
  ID.DiscoverTip : " DAPPはあなたのウォレットを使用します。 このウェブサイトにウォレット情報を提供してよろしいですか？",
  ID.DiscoverSearch : "DAPP検索",
  ID.DiscoverSearchTip : "DAPPウエブアドレスを入力",
  ID.DiscoverSearchTip1 : "検索内容を入力下さい",
  ID.DiscoverComment : "誰もが検索中",
  ID.DiscoverSearchHistory : "履歴検索",

  ID.Kyf : "NFT",
  ID.KyfFloorPrice : "フロア価格",
  ID.KyfTokenId : "Token Id:",
  ID.KyfShow : "見せる",
  ID.KyfDetail : "詳細",
  ID.KyfPiece : "件",

  ID.KyfTransfer : "プレゼント",
  ID.KyfReceive : "受入",

};